/** design-sync preview support: mdi icon paths for every `mdi:*` name
 * this frontend uses. Regenerate with ds-gen-icon-map (see .design-sync/NOTES.md)
 * after adding icons. Tree-shaken: only these paths reach the DS bundle. */
import {
  mdiAccount,
  mdiAccountOutline,
  mdiAlertCircle,
  mdiAlertCircleCheckOutline,
  mdiAlertOctagon,
  mdiArchiveArrowUpOutline,
  mdiArchiveOutline,
  mdiArrowLeft,
  mdiAutoFix,
  mdiBatteryAlert,
  mdiBatteryChargingOutline,
  mdiBatterySync,
  mdiBellAlert,
  mdiBookOpenVariant,
  mdiCalendarAlert,
  mdiCalendarArrowRight,
  mdiCalendarClock,
  mdiCalendarMonth,
  mdiCalendarRemove,
  mdiCalendarSync,
  mdiCalendarToday,
  mdiCalendarWeek,
  mdiCalendarWeekBegin,
  mdiCamera,
  mdiCartArrowDown,
  mdiChartLine,
  mdiChartLineVariant,
  mdiCheck,
  mdiCheckCircle,
  mdiCheckCircleOutline,
  mdiCheckboxMultipleMarkedOutline,
  mdiChevronDoubleDown,
  mdiChevronDoubleUp,
  mdiChevronDown,
  mdiChevronRight,
  mdiChevronUp,
  mdiCircle,
  mdiCircleMedium,
  mdiClipboardCheckOutline,
  mdiClipboardPlusOutline,
  mdiClockOutline,
  mdiClockTimeFourOutline,
  mdiClose,
  mdiCogOutline,
  mdiContentSave,
  mdiDelete,
  mdiDeleteOutline,
  mdiDevices,
  mdiDownload,
  mdiEyeOffOutline,
  mdiEyeOutline,
  mdiFileDelimitedOutline,
  mdiFileDocumentOutline,
  mdiFilterVariant,
  mdiFloorPlan,
  mdiFolderOutline,
  mdiFormatListChecks,
  mdiHelpCircleOutline,
  mdiHomeFloor1,
  mdiImageOutline,
  mdiInformationOutline,
  mdiLinkVariant,
  mdiLinkVariantOff,
  mdiLinkVariantPlus,
  mdiMagnify,
  mdiMapMarkerOutline,
  mdiMenuDown,
  mdiNfcVariant,
  mdiNoteTextOutline,
  mdiOpenInNew,
  mdiPackageVariant,
  mdiPackageVariantClosed,
  mdiPackageVariantClosedPlus,
  mdiPaperclip,
  mdiPauseCircleOutline,
  mdiPencil,
  mdiPlaylistPlus,
  mdiPlus,
  mdiPlusBox,
  mdiPlusMinusVariant,
  mdiPrinterOutline,
  mdiPulse,
  mdiQrcode,
  mdiReceiptTextOutline,
  mdiRefresh,
  mdiRestart,
  mdiShieldCheck,
  mdiSkipNext,
  mdiTable,
  mdiTagOutline,
  mdiTrayArrowDown,
  mdiTrendingUp,
  mdiUpdate,
  mdiUpload,
  mdiViewGridOutline,
  mdiViewGridPlusOutline,
  mdiWrench,
  mdiWrenchClock,
} from "@mdi/js";

export const DS_MDI_PATHS: Record<string, string> = {
  "mdi:account": mdiAccount,
  "mdi:account-outline": mdiAccountOutline,
  "mdi:alert-circle": mdiAlertCircle,
  "mdi:alert-circle-check-outline": mdiAlertCircleCheckOutline,
  "mdi:alert-octagon": mdiAlertOctagon,
  "mdi:archive-arrow-up-outline": mdiArchiveArrowUpOutline,
  "mdi:archive-outline": mdiArchiveOutline,
  "mdi:arrow-left": mdiArrowLeft,
  "mdi:auto-fix": mdiAutoFix,
  "mdi:battery-alert": mdiBatteryAlert,
  "mdi:battery-charging-outline": mdiBatteryChargingOutline,
  "mdi:battery-sync": mdiBatterySync,
  "mdi:bell-alert": mdiBellAlert,
  "mdi:book-open-variant": mdiBookOpenVariant,
  "mdi:calendar-alert": mdiCalendarAlert,
  "mdi:calendar-arrow-right": mdiCalendarArrowRight,
  "mdi:calendar-clock": mdiCalendarClock,
  "mdi:calendar-month": mdiCalendarMonth,
  "mdi:calendar-remove": mdiCalendarRemove,
  "mdi:calendar-sync": mdiCalendarSync,
  "mdi:calendar-today": mdiCalendarToday,
  "mdi:calendar-week": mdiCalendarWeek,
  "mdi:calendar-week-begin": mdiCalendarWeekBegin,
  "mdi:camera": mdiCamera,
  "mdi:cart-arrow-down": mdiCartArrowDown,
  "mdi:chart-line": mdiChartLine,
  "mdi:chart-line-variant": mdiChartLineVariant,
  "mdi:check": mdiCheck,
  "mdi:check-circle": mdiCheckCircle,
  "mdi:check-circle-outline": mdiCheckCircleOutline,
  "mdi:checkbox-multiple-marked-outline": mdiCheckboxMultipleMarkedOutline,
  "mdi:chevron-double-down": mdiChevronDoubleDown,
  "mdi:chevron-double-up": mdiChevronDoubleUp,
  "mdi:chevron-down": mdiChevronDown,
  "mdi:chevron-right": mdiChevronRight,
  "mdi:chevron-up": mdiChevronUp,
  "mdi:circle": mdiCircle,
  "mdi:circle-medium": mdiCircleMedium,
  "mdi:clipboard-check-outline": mdiClipboardCheckOutline,
  "mdi:clipboard-plus-outline": mdiClipboardPlusOutline,
  "mdi:clock-outline": mdiClockOutline,
  "mdi:clock-time-four-outline": mdiClockTimeFourOutline,
  "mdi:close": mdiClose,
  "mdi:cog-outline": mdiCogOutline,
  "mdi:content-save": mdiContentSave,
  "mdi:delete": mdiDelete,
  "mdi:delete-outline": mdiDeleteOutline,
  "mdi:devices": mdiDevices,
  "mdi:download": mdiDownload,
  "mdi:eye-off-outline": mdiEyeOffOutline,
  "mdi:eye-outline": mdiEyeOutline,
  "mdi:file-delimited-outline": mdiFileDelimitedOutline,
  "mdi:file-document-outline": mdiFileDocumentOutline,
  "mdi:filter-variant": mdiFilterVariant,
  "mdi:floor-plan": mdiFloorPlan,
  "mdi:folder-outline": mdiFolderOutline,
  "mdi:format-list-checks": mdiFormatListChecks,
  "mdi:help-circle-outline": mdiHelpCircleOutline,
  "mdi:home-floor-1": mdiHomeFloor1,
  "mdi:image-outline": mdiImageOutline,
  "mdi:information-outline": mdiInformationOutline,
  "mdi:link-variant": mdiLinkVariant,
  "mdi:link-variant-off": mdiLinkVariantOff,
  "mdi:link-variant-plus": mdiLinkVariantPlus,
  "mdi:magnify": mdiMagnify,
  "mdi:map-marker-outline": mdiMapMarkerOutline,
  "mdi:menu-down": mdiMenuDown,
  "mdi:nfc-variant": mdiNfcVariant,
  "mdi:note-text-outline": mdiNoteTextOutline,
  "mdi:open-in-new": mdiOpenInNew,
  "mdi:package-variant": mdiPackageVariant,
  "mdi:package-variant-closed": mdiPackageVariantClosed,
  "mdi:package-variant-closed-plus": mdiPackageVariantClosedPlus,
  "mdi:paperclip": mdiPaperclip,
  "mdi:pause-circle-outline": mdiPauseCircleOutline,
  "mdi:pencil": mdiPencil,
  "mdi:playlist-plus": mdiPlaylistPlus,
  "mdi:plus": mdiPlus,
  "mdi:plus-box": mdiPlusBox,
  "mdi:plus-minus-variant": mdiPlusMinusVariant,
  "mdi:printer-outline": mdiPrinterOutline,
  "mdi:pulse": mdiPulse,
  "mdi:qrcode": mdiQrcode,
  "mdi:receipt-text-outline": mdiReceiptTextOutline,
  "mdi:refresh": mdiRefresh,
  "mdi:restart": mdiRestart,
  "mdi:shield-check": mdiShieldCheck,
  "mdi:skip-next": mdiSkipNext,
  "mdi:table": mdiTable,
  "mdi:tag-outline": mdiTagOutline,
  "mdi:tray-arrow-down": mdiTrayArrowDown,
  "mdi:trending-up": mdiTrendingUp,
  "mdi:update": mdiUpdate,
  "mdi:upload": mdiUpload,
  "mdi:view-grid-outline": mdiViewGridOutline,
  "mdi:view-grid-plus-outline": mdiViewGridPlusOutline,
  "mdi:wrench": mdiWrench,
  "mdi:wrench-clock": mdiWrenchClock,
};
