#!/usr/bin/with-contenv sh
# Patch HA s6 run script to include libfaketime alongside jemalloc.
# Without this, the run script overwrites LD_PRELOAD with only jemalloc,
# removing the faketime library set via compose.yaml.

FAKETIME_LIB="/usr/local/lib/faketime/libfaketime.so.1"
HA_RUN="/run/s6/legacy-services/home-assistant/run"

# Only patch if faketime is enabled and the run script exists
if [ -z "$FAKETIME_TIMESTAMP_FILE" ]; then
    echo "[faketime-patch] FAKETIME_TIMESTAMP_FILE not set, skipping"
    exit 0
fi

if [ ! -f "$FAKETIME_LIB" ]; then
    echo "[faketime-patch] libfaketime.so.1 not found, skipping"
    exit 0
fi

# Wait for the run script to be generated by s6
for i in $(seq 1 30); do
    if [ -f "$HA_RUN" ]; then
        break
    fi
    sleep 0.5
done

if [ ! -f "$HA_RUN" ]; then
    echo "[faketime-patch] HA run script not found after 15s, skipping"
    exit 0
fi

# Check if already patched
if grep -q "libfaketime" "$HA_RUN"; then
    echo "[faketime-patch] Already patched"
    exit 0
fi

# Patch: append libfaketime to the jemalloc LD_PRELOAD line
if grep -q 'LD_PRELOAD="/usr/local/lib/libjemalloc.so.2"' "$HA_RUN"; then
    sed -i 's|LD_PRELOAD="/usr/local/lib/libjemalloc.so.2"|LD_PRELOAD="/usr/local/lib/libjemalloc.so.2 /usr/local/lib/faketime/libfaketime.so.1"|' "$HA_RUN"
    echo "[faketime-patch] Patched LD_PRELOAD to include libfaketime"
else
    echo "[faketime-patch] Could not find jemalloc LD_PRELOAD line to patch"
fi
